Parameters:
  EnvironmentName:
    Description: The name of the environment (e.g., dev, prod)
    Type: String

Resources:
  CloudformationTemplatesBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${EnvironmentName}-rtc-cloudformation-templates'
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256