AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Sample Template: This template sets up the base search system.'

Parameters:
  EnvironmentName:
    Description: The name of the environment (e.g., dev, prod)
    Type: String
  EnvironmentNameCamelCase:
    Description: The name of the environment (e.g., dev, prod) in CamelCase for supporting multiple environments in same account without conflicts.
    Type: String
  VendorSuffix:
    Description: Unique vendor suffix for the bucket.
    Type: String
  VendorSuffixCamelCase:
    Description: Unique vendor suffix in CamelCase for supporting multiple vendors under the same account.
    Type: String
  UserPoolId:
    Description: The ID of the Cognito User Pool
    Type: String
  IdentityPoolId:
    Description: The ID of the Cognito Identity Pool
    Type: String

Resources:
  CognitoOpenSearchRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub 'RtcCognitoOpenSearchRole${EnvironmentNameCamelCase}${VendorSuffixCamelCase}'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "opensearchservice.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub 'RtcCognitoOpenSearchAccess${EnvironmentNameCamelCase}${VendorSuffixCamelCase}'
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "cognito-idp:DescribeUserPool"
                  - "cognito-idp:CreateUserPoolClient"
                  - "cognito-idp:DeleteUserPoolClient"
                  - "cognito-idp:DescribeUserPoolClient"
                  - "cognito-idp:AdminInitiateAuth"
                  - "cognito-idp:AdminUserGlobalSignOut"
                  - "cognito-idp:ListUserPoolClients"
                  - "cognito-identity:DescribeIdentityPool"
                  - "cognito-identity:UpdateIdentityPool"
                  - "cognito-identity:SetIdentityPoolRoles"
                  - "cognito-identity:GetIdentityPoolRoles"
                Resource:
                  - "arn:aws:cognito-identity:*:*:identitypool/*"
                  - "arn:aws:cognito-idp:*:*:userpool/*"
              - Effect: "Allow"
                Action:
                  - "iam:PassRole"
                Resource: "arn:aws:iam::*:role/*"
                Condition:
                  StringLike:
                    iam:PassedToService: "cognito-identity.amazonaws.com"
  MyDomain:
    Type: "AWS::OpenSearchService::Domain"
    Properties:
      DomainName: !Sub 'rtc-classifieds-${EnvironmentName}-${VendorSuffix}'
      EngineVersion: "OpenSearch_2.15"
      ClusterConfig:
        InstanceType: "t3.small.search"
        InstanceCount: 1
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10
      EncryptionAtRestOptions:
        Enabled: true
      NodeToNodeEncryptionOptions:
        Enabled: true
      DomainEndpointOptions:
        EnforceHTTPS: true
        TLSSecurityPolicy: "Policy-Min-TLS-1-2-2019-07"
        CustomEndpointEnabled: false
        # CustomEndpointCertificateArn: "arn:aws:acm:us-east-1:637423414889:certificate/dd0fda77-8882-4f2c-8eee-cf8e957e57d3"
        # CustomEndpoint: "search.climateaware-dev.eco"
      CognitoOptions:
        Enabled: true
        UserPoolId: !Ref UserPoolId
        IdentityPoolId: !Ref IdentityPoolId
        RoleArn: !GetAtt CognitoOpenSearchRole.Arn
      AdvancedSecurityOptions:
        AnonymousAuthEnabled: false
        Enabled: true
        InternalUserDatabaseEnabled: false
        MasterUserOptions:
          MasterUserARN: "arn:aws:iam::637423414889:user/tzmijewski"

