service: goclassifieds-api
provider:
  name: aws
  runtime: go1.x
package:
  individually: true
  exclude:
    - ./**
  include:
    - bazel-bin/apps/ads/linux_amd64_pure_stripped/**
functions:
  ads-api:
    handler: bazel-bin/apps/ads/linux_amd64_pure_stripped/ads
    package:
      include:
        - bazel-bin/apps/ads/linux_amd64_pure_stripped/ads
      exclude:
        - bazel-bin/apps/ads/linux_amd64_pure_stripped/**
    events:
      - http:
          path: /ads
          method: any
      - http:
          path: /ads/{any+}
          method: any