service: chrome
frameworkVersion: '3'
plugins:
  - serverless-prune-plugin
  - serverless-plugin-chrome
custom:
  chrome:
    flags:
      - --window-size=1280,1696 # Letter size
      - --hide-scrollbars
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  timeout: 10
  environment:
    PAGE_LOAD_TIMEOUT: 20000
    LOGGING: true
package:
  individually: false
  patterns:
    - '!./**'
    - bazel-bin/func/screenshot/screenshot.js
resources:
  Resources:
    ChromeRole:
      Type: AWS::IAM::Role
      Properties:
        Path: "/"
        RoleName: chrome-${opt:region, 'us-east-1'}-lambdaRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                  - apigateway.amazonaws.com
              Action: sts:AssumeRole   
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        Policies:
          - PolicyName: statsy-scrapper-lambda
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - logs:DescribeLogGroups
                    - logs:DescribeLogStreams
                    - logs:GetLogEvents
                    - logs:FilterLogEvents
                  Resource:
                    - 'Fn::Join':
                      - ':'
                      -
                        - 'arn:aws:logs'
                        - Ref: 'AWS::Region'
                        - Ref: 'AWS::AccountId'
                        - 'log-group:/aws/lambda/*:*:*'
                - Effect: "Allow"
                  Action:
                    - "lambda:InvokeFunction"
                  Resource: "*"
                - Effect: "Allow"
                  Action:
                    - "execute-api:Invoke"
                    - "execute-api:ManageConnections"
                  Resource: "*"
functions:
  Screenshot:
    handler: bazel-bin/func/screenshot/screenshot.handler
    role: ChromeRole
    memorySize: 1536
    timeout: 30
    environment:
      STAGE: ${opt:stage, 'dev'}
    events:
      - http:
          path: screenshot
          method: get