service: goclassifieds-api
provider:
  name: aws
  runtime: go1.x
package:
  exclude: # By default exclude all files
    - ./**
  include: # Then start adding the relevant files/folder to package
    - bazel-bin/apps/**
functions:
  ads-api:
    handler: "bazel-bin/apps/ads/linux_amd64_pure_stripped/ads"
    events:
      - http:
          path: /ads
          method: any
      - http:
          path: /ads/{any+}
          method: any